services:
  web:
    container_name: web
    image: node:lts
    command: bash /tool/start.sh
    ports:
      - "3000:3000" # Nuxt.js, React.js, Vue.js
      - "4321:4321" # Astro framework
      - "2222:22"
    volumes:
      - ./tool:/tool
      # if you need to attach a volume, you can add it here
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    healthcheck:
      test: ["CMD","bash","-c","echo 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 30s